---
- hosts: localhost
  tasks:
  - name: Download tomcat 8
    become: yes
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: ec2-user
      group: ec2-user
  - name: Download tomcat url
    become: yes
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.59/bin/apache-tomcat-9.0.59.tar.gz
      dest: /opt/tomcat/
      force: yes
      mode: 0755
      group: ec2-user
      owner: ec2-user
  - name: Unzip gz log
    command: "sudo tar -xvzf apache-tomcat-9.0.59.tar.gz"
    args:
      chdir: /opt/tomcat/
  - name: Run Tomcat
    shell: ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.59/bin
