- name: Install Java 1.8
  become: true
  yum: name=java-1.8.0-openjdk state=present

- name: add group "tomcat"
  become: true
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  become: yes
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.59/bin/apache-tomcat-9.0.59.tar.gz
    dest: /opt/tomcat
    mode: 0755
    group: tomcat
    owner: tomcat
- name: Unzip gz log
  command: "sudo tar -xvzf apache-tomcat-9.0.59.tar.gz"
  args:
    chdir: /opt/tomcat

- name: Symlink install directory
  become: true
  file: src=/opt/tomcat/apache-tomcat-9.0.59 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  become: true
  file:
    path: /usr/share/tomcat/
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
    mode: '0755'
- name: Configure Tomcat server
  template:
    src: server.j2
    dest: /usr/share/tomcat/conf/server.xml
  notify: restart tomcat

- name: Configure Tomcat users
  become: true
  template:
    src: tomcat-users.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restart tomcat

- name: copy artifact
  become: true
  copy:
    src: dptweb-1.0.war
    dest: /usr/share/tomcat/webapps/
    #- name: Install Tomcat init script
    #  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  become: true
  command: "sudo /usr/share/tomcat/bin/startup.sh"
    #  service:/usr/share/tomcat/ name=tomcat state=started enabled=yes
